export const NOTIFICATION_EVENT_STATE = {
  BELOW_MINIMUM: "BELOW_MINIMUM",
  NEAR_MINIMUM: "NEAR_MINIMUM",

  EXPIRED: "EXPIRED",
  NEAR_EXPIRATION: "NEAR_EXPIRATION",

  STOCK_UPDATED: "STOCK_UPDATED",

  SUGGEST_REPLENISHMENT: "SUGGEST_REPLENISHMENT",
};
