CREATE TABLE IF NOT EXISTS "Usuario" (
	"id_usuario" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(255) NOT NULL,
	"papel" VARCHAR(255) NOT NULL,
	"senha_hash" BYTEA NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"ativo" BOOLEAN NOT NULL,
	"data_criacao" DATE NOT NULL,
	PRIMARY KEY("id_usuario")
);


CREATE TABLE IF NOT EXISTS "Notificacao" (
	"id_notificacao" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tipo" VARCHAR(255) NOT NULL,
	"lida" BOOLEAN NOT NULL,
	"mensagem" VARCHAR(255) NOT NULL,
	"titulo" VARCHAR(255) NOT NULL,
	"tipo_referencia" VARCHAR(255) NOT NULL,
	"id_usuario" INTEGER NOT NULL,
	PRIMARY KEY("id_notificacao")
);


CREATE TABLE IF NOT EXISTS "Produto" (
	"cod_produto" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(255) NOT NULL,
	"descricao" VARCHAR(255),
	"categoria" VARCHAR(255) NOT NULL,
	"estoque_atual" INTEGER NOT NULL,
	"estoque_minimo" INTEGER NOT NULL,
	"data_cadastro" DATE NOT NULL,
	"data_validade" DATE,
	"valor_unitario" DECIMAL NOT NULL,
	PRIMARY KEY("cod_produto")
);


CREATE TABLE IF NOT EXISTS "Movimentacao" (
	"id_movimentacao" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tipo_movimento" VARCHAR(255) NOT NULL,
	"data_movimento" DATE NOT NULL,
	"quantidade" INTEGER NOT NULL,
	"observacao" VARCHAR(255),
	"id_usuario" INTEGER NOT NULL,
	"cod_produto" INTEGER NOT NULL,
	PRIMARY KEY("id_movimentacao")
);


CREATE TABLE IF NOT EXISTS "ItemRequisicao" (
	"id_item_requisicao" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"quantidade" INTEGER NOT NULL,
	"observacao" VARCHAR(255),
	"cod_produto" INTEGER NOT NULL,
	"id_requisicao" INTEGER NOT NULL,
	PRIMARY KEY("id_item_requisicao")
);


CREATE TABLE IF NOT EXISTS "Requisicao" (
	"id_requisicao" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"titulo" VARCHAR(255) NOT NULL,
	"descricao" VARCHAR(255),
	"motivo" VARCHAR(255),
	"prioridade" VARCHAR(255),
	"status" VARCHAR(255) NOT NULL,
	"data_criacao" DATE NOT NULL,
	"id_usuario" INTEGER NOT NULL,
	PRIMARY KEY("id_requisicao")
);


CREATE TABLE IF NOT EXISTS "LLM" (
	"id_mensagem" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"prompt" VARCHAR(255) NOT NULL,
	"local" VARCHAR(255) NOT NULL,
	"resposta" VARCHAR(255) NOT NULL,
	"id_usuario" INTEGER NOT NULL,
	PRIMARY KEY("id_mensagem")
);

CREATE TABLE IF NOT EXISTS "LogImportacao" (
	"id_log_importacao" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nome_arquivo" VARCHAR(255) NOT NULL,
	"qntd_registros" INTEGER NOT NULL,
	"data_importacao" DATE NOT NULL,
	"status" VARCHAR(255) NOT NULL,
	"msg_erro" VARCHAR(255),
	"id_usuario" INTEGER NOT NULL,
	PRIMARY KEY("id_log_importacao")
);


CREATE TABLE IF NOT EXISTS "LogLLM" (
	"id_log_llm" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tokens" TEXT NOT NULL,
	"tm_resposta_ms" TIMETZ NOT NULL,
	"data_hora" TIMESTAMP NOT NULL,
	"tipo_consulta" TIME NOT NULL,
	"id_msg_llm" INTEGER NOT NULL,
	PRIMARY KEY("id_log_llm")
);

CREATE TABLE IF NOT EXISTS "logEmail" (
	"id_log_email" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"destinatario" VARCHAR(255) NOT NULL,
	"assunto" VARCHAR(255),
	"corpo" VARCHAR(255),
	"status_envio" VARCHAR(255),
	"data_envia" DATE NOT NULL,
	"erro_envio" VARCHAR(255),
	"id_requisicao" INTEGER NOT NULL,
	PRIMARY KEY("id_log_email")
);



ALTER TABLE "Notificacao"
ADD FOREIGN KEY("id_usuario") REFERENCES "Usuario"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "LogImportacao"
ADD FOREIGN KEY("id_usuario") REFERENCES "Usuario"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "LLM"
ADD FOREIGN KEY("id_usuario") REFERENCES "Usuario"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "LogLLM"
ADD FOREIGN KEY("id_msg_llm") REFERENCES "LLM"("id_mensagem")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Movimentacao"
ADD FOREIGN KEY("id_usuario") REFERENCES "Usuario"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Movimentacao"
ADD FOREIGN KEY("cod_produto") REFERENCES "Produto"("cod_produto")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ItemRequisicao"
ADD FOREIGN KEY("cod_produto") REFERENCES "Produto"("cod_produto")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ItemRequisicao"
ADD FOREIGN KEY("id_requisicao") REFERENCES "Requisicao"("id_requisicao")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "logEmail"
ADD FOREIGN KEY("id_requisicao") REFERENCES "Requisicao"("id_requisicao")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Requisicao"
ADD FOREIGN KEY("id_usuario") REFERENCES "Usuario"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;